server:
  port: 443
  http2:
    enabled: true
  ssl:
    key-store-type: PKCS12 # The format used for the keystore. It could be set to JKS in case it is a JKS file
    key-store: classpath:keystore/lostfoundpets.p12 # The path to the keystore containing the certificate
    key-store-password: 12345678 # The password used to generate the certificate
    key-alias: lostfoundpets # The alias mapped to the certificate
    enabled: true

spring:
  application:
    name: telebot
  cloud:
    gcp:
      sql:
        instance-connection-name: braided-rush-383415:us-central1:postgres-01
        database-name: telebot

  datasource:
    username: postgres
    password: qwert12345
    hikari:
      maximum-pool-size: 10

telegrambot:
  userName: @Choo1bot
  botToken: 710277744:AAHze1GFOc7yTxPjCWXrckQ-azKA7bYTW0Y
  webHookPath: https://34.30.224.192/
  adminId:

eventservice:
  period: 600000