CREATE TABLE TELEBOT_USER
(
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    date_created  DATE DEFAULT SYSDATE NOT NULL,
    date_updated  DATE DEFAULT SYSDATE,
    chat_id       NUMBER               NOT NULL,
    user_id       NUMBER               NOT NULL,
    user_name     NVARCHAR2(36)        NOT NULL,
    user_name_ext NVARCHAR2(200)       NOT NULL,

        CONSTRAINT telebot_user_pk PRIMARY KEY (id)
);